### ISSUE TITLE
Responded when not summoned

### ISSUE THREAD

**Issue by pseudopsud** [Lunar-Dawn/FlagWaverBotReborn#3]
In this comment https://www.reddit.com/r/vexillology/comments/uyvtnt/are_windsocks_any_less_flags_than_any_other_flags/ia8eoec?context=99

the bot responded to the comment
"I have to admit I spent too much time wondering what the movie _Die Hard_ had to do with windsocks, and trying to remember of a scene prominently featuring windsocks in it (or the sequels)." which does not contain an activation phrase

**Comment by Lunar-Dawn** [comment]
Is that your comment? People like to ninja edit their comments with the summon command in, so if it isn't your comment that's most likely why the bot responded to it.
